services:
  - type: web
    name: sales-predictor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python app/model.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
